# Generated by Django 2.1.2 on 2018-10-06 16:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('roll', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=70)),
                ('year', models.CharField(blank=True, max_length=30, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
                ('team', models.CharField(blank=True, max_length=30, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
