# Generated by Django 2.1.2 on 2018-10-07 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0002_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='branch',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
