# Generated by Django 2.1.2 on 2018-10-09 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0003_member_branch'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pending_User',
            fields=[
                ('roll', models.IntegerField(default=0, primary_key=True, serialize=False)),
                ('password', models.CharField(max_length=30)),
                ('name', models.CharField(max_length=30)),
                ('contact_no', models.CharField(max_length=10)),
                ('email', models.EmailField(max_length=70)),
                ('branch', models.CharField(blank=True, max_length=30, null=True)),
                ('year', models.CharField(blank=True, max_length=30, null=True)),
                ('profile_picture', models.ImageField(blank=True, null=True, upload_to='')),
                ('role', models.CharField(blank=True, max_length=30, null=True)),
                ('team', models.CharField(blank=True, max_length=30, null=True)),
            ],
        ),
    ]
