# Generated by Django 2.1.2 on 2018-10-16 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0005_member_pending_status'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Pending_User',
        ),
        migrations.AddField(
            model_name='member',
            name='password',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
