# Generated by Django 2.1.2 on 2018-10-18 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0007_auto_20181018_2329'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='branch',
            field=models.CharField(blank=True, choices=[(1, 'First Year'), (2, 'Second Year'), (3, 'Third Year'), (4, 'Fourth Year')], max_length=30, null=True),
        ),
    ]
