# Generated by Django 2.1.2 on 2018-10-19 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0008_auto_20181018_2336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='branch',
            field=models.CharField(blank=True, choices=[('CSE', 'CSE'), ('Civil', 'Civil'), ('Electronics', 'Electronics'), ('Electrical', 'Electrical')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, choices=[('Volunteer', 'Volunteer'), ('Coordinator', 'Coordinator')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='team',
            field=models.CharField(blank=True, choices=[('Technical Team', 'Technical Team'), ('Documentation Team', 'Documentation Team'), ('Design Team', 'Design Team'), ('Sponsorship Team', 'Sponsorship Team')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='member',
            name='year',
            field=models.CharField(blank=True, choices=[('First Year', 'First Year'), ('Second Year', 'Second Year'), ('Third Year', 'Third Year'), ('Fourth Year', 'Fourth Year')], max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='deadline',
            field=models.DateField(),
        ),
    ]
