# Generated by Django 2.1.2 on 2018-10-20 15:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0011_auto_20181019_2308'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='pending_status',
        ),
    ]
