# Generated by Django 2.1.2 on 2018-10-20 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0012_remove_member_pending_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='pending_status',
            field=models.BooleanField(default=True),
        ),
    ]
