# Generated by Django 2.1.2 on 2018-11-28 15:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0019_announcement'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='announcement',
            name='project',
        ),
    ]
