# Generated by Django 2.0 on 2018-12-01 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0020_remove_announcement_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='finished',
            field=models.CharField(blank=True, choices=[('Yes', 'Yes'), ('No', 'No')], default='No', max_length=30, null=True),
        ),
    ]
