# Generated by Django 2.1.2 on 2018-12-05 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portal', '0021_auto_20181201_1630'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(blank=True, choices=[('Volunteer', 'Volunteer'), ('Coordinator', 'Coordinator'), ('Assistant Coordinator', 'Assistant Coordinator'), ('Faculty', 'Faculty')], max_length=30, null=True),
        ),
    ]
